# Generated by Django 4.0 on 2022-04-06 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_employeeexperience_employeeeducation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeeducation',
            old_name='percentagepghsc',
            new_name='percentagehsc',
        ),
    ]
